apiVersion: apps/v1
kind: Deployment
metadata:
  name: pern-backend
  labels:
    app: pern-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: pern-backend
  template:
    metadata:
      labels:
        app: pern-backend
    spec:
      containers:
        - name: pern-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
