apiVersion: v1
kind: Service
metadata:
  name: pern-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: pern-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.port }}
