apiVersion: v1
kind: Service
metadata:
  name: pern-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: pern-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port }}
